// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "DriveBase.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
const double DriveBase::pi = 3.14159;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

DriveBase::DriveBase() : Subsystem("DriveBase") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    frontLeftDrive = RobotMap::driveBaseFrontLeftDrive;
    frontRightDrive = RobotMap::driveBaseFrontRightDrive;
    rearLeftDrive = RobotMap::driveBaseRearLeftDrive;
    rearRightDrive = RobotMap::driveBaseRearRightDrive;
    frontLeftPos = RobotMap::driveBaseFrontLeftPos;
    frontLeftSteer = RobotMap::driveBaseFrontLeftSteer;
    frontLeft = RobotMap::driveBaseFrontLeft;
    frontRightPos = RobotMap::driveBaseFrontRightPos;
    frontRightSteer = RobotMap::driveBaseFrontRightSteer;
    frontRigt = RobotMap::driveBaseFrontRigt;
    rearLeftPos = RobotMap::driveBaseRearLeftPos;
    rearLeftSteer = RobotMap::driveBaseRearLeftSteer;
    rearLeft = RobotMap::driveBaseRearLeft;
    rearRightPos = RobotMap::driveBaseRearRightPos;
    rearRightSteer = RobotMap::driveBaseRearRightSteer;
    rearRight = RobotMap::driveBaseRearRight;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void DriveBase::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

