// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEBASE_H
#define DRIVEBASE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveBase: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<SpeedController> frontLeftDrive;
	std::shared_ptr<SpeedController> frontRightDrive;
	std::shared_ptr<SpeedController> rearLeftDrive;
	std::shared_ptr<SpeedController> rearRightDrive;
	std::shared_ptr<AnalogInput> frontLeftPos;
	std::shared_ptr<CANTalon> frontLeftSteer;
	std::shared_ptr<PIDController> frontLeft;
	std::shared_ptr<AnalogInput> frontRightPos;
	std::shared_ptr<CANTalon> frontRightSteer;
	std::shared_ptr<PIDController> frontRigt;
	std::shared_ptr<AnalogInput> rearLeftPos;
	std::shared_ptr<CANTalon> rearLeftSteer;
	std::shared_ptr<PIDController> rearLeft;
	std::shared_ptr<AnalogInput> rearRightPos;
	std::shared_ptr<CANTalon> rearRightSteer;
	std::shared_ptr<PIDController> rearRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	DriveBase();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	const static double pi;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
